spring.application.name=finaleService
spring.security.oauth2.client.registration.github.client-id=Ov23li541gAAxiUeCk4b
spring.security.oauth2.client.registration.github.client-secret=47a2050d17feebc51ae9ca4a6f40b41b671a293a

server.port=8010