spring.application.name=jwtApiGateway
server.port=8080
management.endpoints.web.exposure.include=*
management.endpoint.gateway.access=unrestricted
secret=u1J5xG0yW9nGq7pT8eL3rK6zV4sY2cQ9mN0tB5fH7dE1xU2aR8vO3jP6wL4qZ9y
