spring.application.name=loginService
server.port=5080
spring.config.import=configserver:http://localhost:8888
logging.level.org.springframework.security=trace
management.endpoints.web.exposure.include=*