spring:
  application:
    name: Day10_ProfileAndRunner
  config:
    activate:
      on-profile: dev

server:
  port: 5050

com:
  example:
    demo:
      custom: custom property



---

spring:
  config:
    activate:
      on-profile: prod

logging:
  level:
    '[org.springframework]': TRACE

server:
  port: 6060
