server:
  port: ${port:0}

spring:
  application:
    name: bookService

  config:
    import: "configserver:http://localhost:8888"

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

management:
  endpoints:
    web:
      exposure:
        include: "*"
