spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test3
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update       
    show-sql: true           
  main:
    web-application-type: none
  application:
    name: SpringCaseStudy
logging:
  level:
    org.springframework.jdbc: debug
    org.springframework.data.jpa: debug
    org.hibernate.SQL: debug

